modified pre-commit script

diff --git a/environment/development/githooks/pre-commit b/environment/development/githooks/pre-commit
--- a/environment/development/githooks/pre-commit
+++ b/environment/development/githooks/pre-commit
@@ -20,8 +20,11 @@ fi
 # Find files with trailing whitespace
 for FILE in `exec git diff-index --check --cached $against -- | sed '/^[+-]/d' | sed -r 's/:[0-9]+:.*//' | uniq` ; do
     # Fix them!
-    sed -i 's/[[:space:]]*$//' "$FILE"
-    git add "$FILE"
+    # sed -i 's/[[:space:]]*$//' "$FILE"
+    # git add "$FILE"
+    echo -e "\e[1;31m\tAborting commit. $FILE containes trailing white spaces.\e[0m" >&2
+    echo -e "\e[1;31m\tFor sublime users, add \"trim_trailing_white_space_on_save\": true, on Preferences -> Settings - User.\e[0m" >&2
+    exit 1
 done
 
 done || exit $?
